[VEC-N/A] Fix UI build failure (#332)
This builds on #331  bumps uikit packages to address the issue seen in this [build failure](https://github.com/archon-research/stl/actions/runs/26039131499/job/76545657109?pr=331).

This also updates the success check to not be incorrectly skipped in case of failures:
<img width="809" height="304" alt="image" src="https://github.com/user-attachments/assets/a262b68c-e287-4794-bb1a-0874466e3064" />

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -66,14 +66,20 @@ jobs:
       - go-ci
       - python-ci
       - ts-ci
-    if: |
-      always() &&
-      !contains(needs.*.result, 'failure') &&
-      !contains(needs.*.result, 'cancelled')
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - name: Report success
-        run: echo 'All required CI checks passed or were skipped.'
+      - name: Check all jobs succeeded
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
+            echo "One or more CI jobs failed"
+            exit 1
+          fi
+          if [[ "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more CI jobs were cancelled"
+            exit 1
+          fi
+          echo 'All required CI checks passed or were skipped.'
 
   call-deploy:
     name: Deploy
